#!/usr/bin/ash
run_hook() {
    modprobe nbd
    for n in 0 1 2 3 4 5 6 7; do
    	PARAMS=`eval "expr \"\\$nbd$n\" "`;
        if [ "x$PARAMS" != "x" ]; then
            HOST=`echo $PARAMS | cut -d : -f 1`
            PORT=`echo $PARAMS | cut -d : -f 2`
            NAME=`echo $PARAMS | cut -d : -f 3`
            RESUME_PARAM="-r"
            NAME_PARAM="-N $NAME"
            if /sbin/nbd-client -r 2>&1 | grep unrecognized; then
                msg "No resume support detected"
                msg "Patch nbd-client & kernel want to prevent fs crashes due to network outages."
                RESUME_PARAM=""
            fi
            if [ "x$NAME" == "x" ]; then
                msg "No named export detected, assuming legacy (nbd-per-port) server"
                /sbin/nbd-client $HOST $PORT /dev/nbd$n -p -s -b 4096 $RESUME_PARAM
            else
                /sbin/nbd-client $NAME_PARAM $HOST $PORT /dev/nbd$n -p -s -b 4096 $RESUME_PARAM
            fi
        fi
    done
}
# vim: set ft=sh ts=4 sw=4 et:
