#!/bin/bash

build() {
    add_module "nbd"
    add_binary "/usr/lib/initcpio/nbd-client" "/sbin/nbd-client"
    add_runscript
}

help() {
    cat<<HELPEOF
This hook allows you to boot from a Network Block Device (NBD).
The 'nbd' hook depends on the 'net' hook, so make sure you add 'net'
before 'nbd' in the hook list in '/etc/mkinitcpio.conf'. You will also
have to remove 'autodetect' from the hook list because the initrd
image will be created on the server and not the client.

Kernel Parameters:

Multiple NBD devices (up to 8) can be specified. Kernel parameters
are numbered nbd0 to nbd7. The format is:
nbd<N>=<server_ip>:[<server_port>][:<export_name>]

nbd<N>        The name of the nbd device. For example nbd0.

<server_ip>   The IP address of the machine running nbd-server.
              This parameter is required.

<server_port> The port on which nbd-server is running. This parameter
              is only required if nbd-server is not running on the
              default port (10809).

<export_name> The name of the export to connect to as specified in
              in /etc/nbd-server/config on the server.
              This parameter is optional (for older nbd servers) 

Also make sure that you set 'root=/dev/nbd0' and the 'ip' parameter
from the 'net' hook (see 'mkinitcpio -H net' for details).
Your hook list may then look like this:
HOOKS="base udev net nbd filesystems"

If your NBD device is encrypted, set 'cryptdevice=/dev/nbd0:nbdcrypt' and
'root=/dev/mapper/nbdcrypt'. You also will have to add the hooks 'usbinput',
'keymap' and 'encrypt' to your hook list after the 'net' and 'nbd' hooks.
Your hook list may then look like this:
HOOKS="base udev net nbd usbinput keymap encrypt filesystems"
HELPEOF
}
